### ISSUE TITLE
When SupportsUserLockout is enabled, Failed Access Count is not reset on successful CheckPassword

### ISSUE THREAD

**Issue by cortex93** [thinktecture/Thinktecture.IdentityServer.v3.AspNetIdentity#17]
Something like
```
if (userManager.SupportsUserLockout)
    await userManager.ResetAccessFailedCountAsync(user.Id);
```
is not done before returning AuthenticateResult if CheckPasswordAsync returns true.

**Comment by brockallen** [comment]
Looks like I added this at some point, but never closed this issue. Can you look at the code and confirm? Thanks.

**Comment by cortex93** [comment]
Yes, you did.
