### ISSUE TITLE
Add Microsoft.Owin.Security.OpenIdConnect (Azure AD)

### ISSUE THREAD

**Issue by lengyangcode** [thinktecture/Thinktecture.IdentityServer.v3.AspNetIdentity#29]
Please the Microsoft OpenID Connect support to this codebase. The IdentityServer v3 core seems to have already supported this feature.  This is the code from the Thinktecture.IdentityServer.v3 Startup.cs file.

var aad = new OpenIdConnectAuthenticationOptions
{
AuthenticationType = "aad",
Caption = "Azure AD",
SignInAsAuthenticationType = signInAsType,
Authority = "https://login.windows.net/4ca9cb4c-5e5f-4be9-b700-c532992a3705",
ClientId = "65bbbda8-8b85-4c9d-81e9-1502330aacba",
RedirectUri = "https://localhost:44333/core/aadcb"
};
app.UseOpenIdConnectAuthentication(aad);

**Comment by leastprivilege** [comment]
What's the question?

**Comment by lengyangcode** [comment]
Currently, the Startup.cs class in this repos supports Google, Facebook, and Twitter.  I asked if you could add the Microsoft OpenID Connect as one of the options in the Startup.cs class.

Thinktecture.IdentityServer.v3.AspNetIdentity-master\source\SelfHost\Startup.cs

Thank you.
Leng.

**Comment by brockallen** [comment]
That code is not part of the core library -- it's just part of the sample hosting application.
