### ISSUE TITLE
EmailConfirmed on LocalAuthentication.

### ISSUE THREAD

**Issue by carzogliore** [thinktecture/Thinktecture.IdentityServer.v3.AspNetIdentity#7]
Hello, 

Just using this version and detect that there is no EmailConfirmed verification on AuthenticateLocalAsync method, it was there in the previous version. Is there a reason that this version does not have that functionality?

Details: 
On https://github.com/thinktecture/Thinktecture.IdentityServer.v3.AspNetIdentity/blob/master/source/AspNetIdentityUserService/AspNetIdentityUserService.cs

This code snipped was part of the public virtual async Task<AuthenticateResult> AuthenticateLocalAsync(string username, string password) on the previous version.

            if (userManager.SupportsUserEmail && 
                !(await userManager.IsEmailConfirmedAsync(user.Id)))
            {
                return null;
            }

I extended it on my local version including that.

Thanks.

Regards.
Roberto.

**Comment by brockallen** [comment]
FYI, a PostAuthenticateLocalAsync method was added to allow a simple virtual to override to add this sort of additional check. HTH

**Comment by carzogliore** [comment]
Thanks Brock.

I'll have a look into this.

Regards,
Roberto,.
